version: 0.0
os: linux

files:
  - source:  /
    destination: /home/ec2-user/spring-github-action
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: tomcat
    mode: 775

hooks:
  BeforeInstall:
    - location: scripts/stop.sh
      timeout: 60
      runas: ec2-user
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 60
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 60
      runas: ec2-user
